name: Tox

on:
  - push
  - pull_request
  - release
  - workflow_dispatch

jobs:
  test-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -r

  test-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
          architecture: x64
      - name: Install pandoc
        run: choco install pandoc
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -r

  test-macos:

    runs-on: macOS-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install pandoc
        run: brew install pandoc
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -r
  
  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - test-linux
      - test-windows
      - test-macos
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ugropy
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1